apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weebodevhub
  description: WeeboDevHub backstage instance for Weebo
  tags:
  - backstage
  - weebodev
  - developerhub
  links:
  - url: https://github.com/batleforc/WeeboDevHub
    title: Repo
    icon: github
  annotations:
    backstage.io/managed-by-location: url:https://github.com/batleforc/WeeboDevHub/blob/main/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/batleforc/WeeboDevHub/blob/main/
    github.com/project-slug: batleforc/WeeboDevHub
spec:
  type: library
  lifecycle: production
  owner: WeeboDev
  system: infra
