services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    volumes:
      - volume-pg:/var/lib/postgresql/data

volumes:
  volume-pg:
